// Errores Api
export const SHOW_ERRORS_API = "SHOW_ERRORS_API";
// Auth
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const CERRAR_SESION = "CERRAR_SESION";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const ADD_USERS = "GET_ALL_USERS";
export const UPDATE_USERS = "GET_ALL_USERS";
export const DELETE_USERS = "GET_ALL_USERS";
export const GET_USER_ME = "GET_USER_ME";
export const USER_CHANGEPASSWORD = "USER_CHANGEPASSWORD";
export const UPDATE_INFO = "UPDATE_INFO";

export const GET_ALL_CURSOS = "GET_ALL_CURSOS";
export const ADD_CURSOS = "ADD_CURSOS";
export const UPDATE_CURSOS = "UPDATE_CURSOS";
export const DELETE_CURSOS = "DELETE_CURSOS";

export const GET_ALL_CATEGORIAS = "GET_ALL_CATEGORIAS";
export const ADD_CATEGORIAS = "ADD_CATEGORIAS";
export const UPDATE_CATEGORIAS = "UPDATE_CATEGORIAS";
export const DELETE_CATEGORIAS = "DELETE_CATEGORIAS";

export const GET_ALL_AGENDAS = "GET_ALL_AGENDAS";
export const ADD_AGENDAS = "ADD_AGENDAS";
export const UPDATE_AGENDAS = "UPDATE_AGENDAS";
export const DELETE_AGENDAS = "DELETE_AGENDAS";
